name: Auto Redeploy

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Redeploy application
        run: |
          umask 077
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd /root/safebot && git pull origin master && source venv/bin/activate && pip install -r requirements.txt && nohup python main.py > logs/infos.log 2>&1 &"
