name: Auto Redeploy

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Redeploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: | 
            cd /root/safebot
            git pull origin master
            source venv/bin/activate
            pkill -f "python main.py"
            pip install -r requirements.txt
            nohup python main.py > logs/infos.log 2>&1 &
