name: Auto Redeploy

on:
  push:
    branches:
      - master

jobs:
  redeploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Redeploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: | 
            npm install pm2 -g
            pm2 -version
            cd /root/safebot
            source venv/bin/activate
            git pull origin master
            pip install -r requirements.txt
            pm2 restart safebot
